POST http://localhost:3003/api/books
Content-Type: application/json

{
  "title": "The Well of Ascension",
  "author": "Brandon Sanderson",
  "pages": 781,
  "yearPublished": 2007,
  "genreTag": 82
}

###
GET http://localhost:3003/api/books

###
POST http://localhost:3003/api/booklogs
Content-Type: application/json

{
  "book": "69a822a5f4d724af63c8cc3d",
  "date": "2025-01-01",
  "currentPage": "100"
}

###
DELETE http://localhost:3003/api/books/699075b25a1825e951b9e8a8